services:
  backend:
    build:
      context: ./backend/taskmanagement
      dockerfile: Dockerfile
    container_name: task-backend
    ports:
      - "8085:8085"
   

  frontend:
    build:
      context: ./frontend/task-frontend
      dockerfile: Dockerfile
    container_name: task-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend